name: integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:

  # Build bundle, doc and check linter
  build:
    name: Build bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run prod


  # Deploy on gnss-master website
  # deploy:
  #   name: Deploy to gnss-master
  #   if: ${{ github.ref == 'refs/heads/main' }}
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   steps:

  #     # Download artifact from build
  #     - name: Download gnss-master bundle
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: dist-gnss-master

  #     # Copy files for deployment
  #     - name: build site
  #       run: |
  #         mkdir -p gnss-master/dist
  #         cp -R dist/*.js gnss-master/dist/

  #     # Deploy
  #     - name: Deploy Dev to gnss master
  #       if: ${{ !startsWith(github.event.head_commit.message, 'release v' ) }}
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./gnss-master
  #         destination_dir: ./gnss-master
  #         enable_jekyll: true